export const SET_LOADING = 'SET_LOADING';
export const GET_DB_RESTAURANTS = 'GET_DB_RESTAURANTS';
export const DB_RESTAURANTS_ERROR = 'FAV_RESTAURANTS_ERROR';
export const GET_DB_BOOKMARKS = 'GET_DB_BOOKMARKS';
export const DB_BOOKMARKS_ERROR = 'DB_BOOKMARKS_ERROR';
