export const SET_LOADING = 'SET_LOADING';

export const GET_DB_RESTAURANTS = 'GET_DB_RESTAURANTS';
export const DB_RESTAURANTS_ERROR = 'FAV_RESTAURANTS_ERROR';

export const GET_DB_BOOKMARKS = 'GET_DB_BOOKMARKS';
export const BOOKMARKS_ERROR = 'BOOKMARKS_ERROR';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';